name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]

jobs:
  call-workflow:
    uses: Frost-ZX/github-actions/.github/workflows/vue-build-and-deploy-pages.yml@main
    with:
      package_manager: pnpm
